### ISSUE TITLE
Slack files 

### ISSUE THREAD

**Issue by camilo246800** [thomasloupe/Slackord#10]
Hi! Excellent work.
Any ideas when slack generates many files for a single channel? Will you know how to unify them or have only 1 per channel?

**Comment by thomasloupe** [comment]
You can combine the JSON into a single flat file just by copying the contents of one JSON file into another, or you can load them independently. I haven't set it up to allow multiple files, but it has been requested a few times. I may choose to implement this at some point.

**Comment by BlueFinBima** [comment]
@camilo246800 I just appended all of the files, and then did a global replace in notepad++ from` ][` to `,` and the files imported fine.  There is a line break between the square brackets, so this needs to be accommodated.

**Comment by thomasloupe** [comment]
Sorry for the delay on this.
Thanks for bringing that point up. This is a good reference for anyone looking to combine multiple JSON files, so I'll be sure to add this to documentation.
