### ISSUE TITLE
[ENH] Implement back-off to allow active threads to reduce

### ISSUE THREAD

**Issue by iainhallam** [thomasloupe/Slackord#101]
**Is your feature request related to a problem? Please describe.**
As per discussion on Discord, when importing more than 1,000 threads, only the first 1,000 are properly threaded because Discord has a limit of that many active threads - once reached, Slackord can no longer create proper threads.

**Describe the solution you'd like**
When getting close to 1,000 active threads, back off the rate of import so that the limit is never breached, even though this will make the process run for several days on large channels.

**Describe alternatives you've considered**
From the discussion on Discord, it seems there isn't one for importing large numbers of threads.

**Comment by thomasloupe** [comment]
Thanks @iainhallam!

This is largely dependent on whether or not we get a response from the following enhancement request directly to Discord.
If Discord were to support my API enhancement, it's the difference between a couple lines of code, and essentially two new features I'd need to create.

For those interested in this functionality, I highly suggest voting this API enhancement request up:
https://github.com/discord/discord-api-docs/discussions/6703

I will continue to monitor that thread for updates, and push for a response from them. I want to support this but I don't want to get halfway through the work then the feature comes out, or in a case where I do all the work, it's good for a week, then I have to remove it all in support of the enhancement. I am watching this very closely though, as it's a top priority.

**Comment by thomasloupe** [comment]
While not an amazing solution to the current issue, one of the newest additions now provides the number of threads each channel will have prior to importing into Discord. This will aid users in closing threads manually until there is some action by Discord to allow apps to programmatically close threads. I am happy to continue actively revisit this as needed to keep Slackord as easy to use as possible.

Please grab the latest release for this feature!
