### ISSUE TITLE
[ENH] Show number of threads for each channel after deconstructing/reconstructing with active thread count warning

### ISSUE THREAD

**Issue by sc0ttkclark** [thomasloupe/Slackord#103]
**Is your feature request related to a problem? Please describe.**
Yes, some times you hit the active threads limit and it would be good to be given the heads up on the channel message counts when importing server/channel.

**Describe the solution you'd like**
Show the total number of threads detected and if it's over 100 (or maybe show it always) include troubleshooting link.

**Describe alternatives you've considered**
Importing smaller date ranges to give myself time to close the threads.

**Additional context**

**Comment by thomasloupe** [comment]
Accepted.
Will work on providing this in the next release.

**Comment by thomasloupe** [comment]
This is now complete and available in the latest release.
