### ISSUE TITLE
v4.3.6 - Attachments being posted as blank "Attachment:" messages

### ISSUE THREAD

**Issue by hijomojo** [thomasloupe/Slackord#104]
**Slackord version: 4.3.6**
 - OS: Windows 11
 - Build: 22621.3880

**Describe the bug**
Attachments aren't actually being attached to messages which should have attachments. Instead, a message from the bot's username is posted with "Attachment:" as the only content of the message.

**To Reproduce**
1. Use an export produced with Slackdump via the Slack server owner account and with a pro subscription active
2. Load Slackord v4.3.6
3. "Import Channel"
4. Select desired channel folder and wait for it to reconstruct
5. Type "/slackord" into whatever channel, in my case I use a channel specifically for typing server-wide commands
6. Wait for it to complete and observe missing attachments

**Additional context**
1. Have tried to import a smaller channel but with no success (have tried channels of 626 messages and 2993, I don't have a smaller channel at the moment)
2. Possibly related (though also possibly a second bug) is that attachments to messages older than some particular age get printed as "File hidden by Slack limit". At first I thought this would be the 90 day limit Slack places on free workspaces, but in the channels I've tested so far, I can see attachment messages slightly older than 90 days printing without this error (note again that I'm working with an export from a Slack Pro workspace, so the 90 day thing shouldn't apply anyway). Messages without attachments are brought in fine, even back many years to the origin of each channel I've tested.
Quite old message with attachment:
![image](https://github.com/user-attachments/assets/215f76cb-0539-44ac-aeaa-4345467d2042)
~99 day old (at time of export) message with attachment:
![image](https://github.com/user-attachments/assets/bbd37db2-f135-4f8b-af9e-267fe7a72761)
These screenshots also show the issue described in the main bug description above.

**Comment by thomasloupe** [comment]
Hey there,

As is mentioned on the readme, there is no guarantee that _all_ Slackdump exports are compatible with Slackord.

What I would recommend, is to try and export the history out via Slack and see if you get the same result. My assumption is that you probably won't encounter that same issue using the basic Slack export.

While I have tried very hard to make all exports from Slackdump compatible with Slackord, there are often times like these where small issues get in the way. I cannot provide support for Slackdump, and instead, have chosen to recommend to most folks to stick with the regular Slack imports to avoid these types of issues.

Additionally, trying to code Slackord for two specifically different types of data exports isn't something a solo developer like myself can really take on. However, I'm open to a forked version, or another branch that would fully support Slackdump exports.

With that in mind, if you were to export this with a normal Slack export and try to import it in and saw this issue, that is something I can assist with. Please let me know how that works out.

**Comment by hijomojo** [comment]
Hey Thomas,

Thanks for getting back to me on this. It had been a few weeks between reading the readme and running my tests, so unfortunately my memory was of the recommendation of Slackdump, rather than the caution of it not being fully compatible. This was a bit compounded by the unintuitive fact that the regular Slack export doesn't include the attachment files themselves whilst Slackdump does; I made the (incorrect) assumption of "substantially more data in the export file = better ability to import everything".

Can confirm, the regular Slack export seems to have worked perfectly, thanks. Really appreciate your work on this; it's helping the tiny community organisation I'm part of migrate away from Slack and its pay-or-lose-your-data model which was incompatible with our practically non-existent funding 🙏🙇‍♂️
