### ISSUE TITLE
Slacklord won't post messages to Discord

### ISSUE THREAD

**Issue by war4peace** [thomasloupe/Slackord#12]
Hello,

I have followed all instructions carefully.
Slacklord joins my server, is shown online, can load the JSON file locally and parses it successfully.
However, "!Slacklord" command does nothing. The bot doesn't react to it.

I'm not sure how to continue from here. Any advice?

**Comment by thomasloupe** [comment]
Hi @war4peace,

Are you typing !slackord, or !slacklord?

**Comment by war4peace** [comment]
Oh. My. God. I am such an idiot.
Of course I was typing „Slacklord” - but in retrospect, you gotta admit, that's a cool nickname :)
The bot works now. It was a problem between keyboard and chair.

**Comment by thomasloupe** [comment]
I agree, it's a pretty killer name. The metalhead in me wishes I had named it differently, but alas.
Glad you got it sorted out! I'll go ahead and close off the issue, enjoy SlackOrd! ;)
