### ISSUE TITLE
Exception attempting to transfer messages to Discord (Linux version)

### ISSUE THREAD

**Issue by kjhosein** [thomasloupe/Slackord#15]
Hello - I'm attempting to import a relatively simple and small message set, and am getting the following error:

```
-----------------------------------------
Parsing completed successfully!

Bot will now attempt to connect to the Discord server...
09:59:09 Discord     Discord.Net v3.7.2 (API v9)

Bot is ready to post messages to Discord. Press any key to stop the connection or posting of messages...
09:59:10 Gateway     Connecting

09:59:10 Gateway     You're using the GuildScheduledEvents gateway intent without listening to any events related to that intent, consider removing the intent from your config.

09:59:10 Gateway     You're using the GuildInvites gateway intent without listening to any events related to that intent, consider removing the intent from your config.

09:59:10 Gateway     Connected

09:59:11 Gateway     Ready

Beginning transfer of Slack messages to Discord...
-----------------------------------------

09:59:19 Gateway     A MessageReceived handler has thrown an unhandled exception.:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Slackord.Slackord.MessageReceived(SocketMessage message) in C:\Users\acid_rain\Desktop\Slackord\Slackord\Program.cs:line 302
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```

System: Linux/Debian 10
Slackord version 2.2.0 for x64

When I run _Slackord_, I can see the bot come online in Discord as well, so I know that connection is working. 

I've tested with importing into both public and private channels. For the private channel, I added the Slackord bot as a member.

--
If I knew anything about C#, I may have gotten further than the somewhat cryptic error message!

Thanks for this tool and any help!

**Comment by thomasloupe** [comment]
Hi @kjhosein,

Thanks for the report.
Is the error being produced regardless of the channel?
Would you be willing to attach the export file here or DM me on Twitter with a link to the export so I can test this against the Linux version of Slackord2?

**Comment by kjhosein** [comment]
Hi Thomas - thanks for the quick reply!

Yep, same error regardless of channel type.

Here's a sample JSON file (renamed with a .txt extension) that I just tried importing into a public Discord channel. 
[2020-03-30.json.txt](https://github.com/thomasloupe/Slackord2/files/9454700/2020-03-30.json.txt)

FWIW, I used the [`slackdump`](https://github.com/rusq/slackdump/blob/master/doc/usage-export.rst) tool to export my Slack channels.
Thanks!

-- Khalid

**Comment by thomasloupe** [comment]
@kjhosein Ahh, this might be the issue then. Could you export the file directly from Slack without using the `slackdump` tool and try it that way? Also, feel free to send that in to this issue as well, or you can do a difference check (diff) on the two files and see the differences. If they are exactly the same, please let me know, but if they are different, it's likely that the formatting for this JSON could be different enough that it's causing issues with Slackord parsing the messages properly.

I see that the message in the output says parsing completed successfully, but I don't see any actual messages that were parsed. This is a good hint that there's an issue with the JSON we didn't expect.

**Comment by kjhosein** [comment]
Yep, you're right. Using the one from Slack worked. 

I did a diff between the two files and they look almost the same, but with different ordering of the elements. The `attachments` element was missing some attributes.

FWIW, I'm attaching the 2 diffs I did (1 inline and the other side-by-side). The 2nd file in the diff is the export from Slack.

[diff.side-by-side.txt](https://github.com/thomasloupe/Slackord2/files/9455885/diff.side-by-side.txt)
[diff.inline.txt](https://github.com/thomasloupe/Slackord2/files/9455886/diff.inline.txt)

BTW, the reason I was using `slackdump` is because it let me export my private channels. I'm using the free version of Slack, so I'm limited to only exporting public channels with their tool.  I'll poke around to see if there's a way to overcome this, but it's probably a new issue. 

Feel free to close this issue out if you can't think of anything else.
Thanks!

**Comment by kjhosein** [comment]
I figured out what was missing - an attribute called `display_name` (it's nested under `user_profile`). For some reason, one of my user's display_name wasn't set. The Slack exporter still includes it but with a empty value. `slackdump` on the other hand leaves it out. 

The ordering didn't matter. If I just manually added it in, it worked fine.

**Comment by kjhosein** [comment]
Just to close out the issue completely, the `slackdump` author [updated the code](https://github.com/rusq/slackdump/issues/123) so that it doesn't omit those attributes that have blank values.

**Comment by thomasloupe** [comment]
@kjhosein Thanks for updating with your findings! I was in the middle of a response right when you closed the issue! 😆 
I was just about to recommend putting in an enhancement request to slackdump to export the values or provide an additional export option for Slackord. Great job by the developer and you for making that happen!

Thanks again for using Slackord2, there are new features coming eventually.
