### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by VileAce** [thomasloupe/Slackord#2]
Would it be possible to have the log stay at the last entry?  When a new entry is added it goes back to the top of the log,  making it difficult to keep up with the status of transferring entries.

Again thanks for a great tool.

**Comment by thomasloupe** [comment]
Hi @VileAce,

Thanks for the kind words. Is this happening for every log entry or only when the bot itself logs an entry?

**Comment by thomasloupe** [comment]
I have fixed this bug. Please see the latest release [here](https://github.com/thomasloupe/Slackord2/releases/tag/v2.0.4).
