### ISSUE TITLE
Null reference access in method `SelectFileAndConvertJson` on Linux

### ISSUE THREAD

**Issue by saltiniroberto** [thomasloupe/Slackord#20]
Lines [212](https://github.com/thomasloupe/Slackord2/blob/master/Slackord_Mac_Linux/Slackord/Program.cs#L212) and [223](https://github.com/thomasloupe/Slackord2/blob/master/Slackord_Mac_Linux/Slackord/Program.cs#L223) raise a "Null reference exception" as the reference `_discordClient` has never been set.

The reference `_discordClient` is set in the method `MainAsync` which is however executed after `SelectFileAndConvertJson`.

**Comment by thomasloupe** [comment]
Thanks, I'll get this fixed today and get a new build out.

**Comment by thomasloupe** [comment]
There is a new build available which fixes this issue, as well as #18 
See: https://github.com/thomasloupe/Slackord2/commit/44227a60dd974365e94f1b96e4f6accff7acd117

Thanks again for raising the issue.
