### ISSUE TITLE
Bot messages are not parsed

### ISSUE THREAD

**Issue by jarommadsen** [thomasloupe/Slackord#21]
I used a bot in an interactive story channel. Without the bot messages a lot of the context is missing. Would you consider adding support for this?

**Comment by thomasloupe** [comment]
Hi @jarommadsen, could you explain what you mean by interactive story channels?
What specific support are you looking for? Please provide some additional detail with screenshots or otherwise to help me understand the request better.

Thanks!

**Comment by jarommadsen** [comment]
@thomasloupe sure thing. Don't worry about the interactive story bit. Just felt like I should offer some context as to why the bot messages were important. I was running a DnD like thing and used a bot to drive a lot of the story elements. All that means is that the bot messages are pretty important.

Here's the first message in the channel that doesn't get picked up by the parser.

```
{
        "bot_id": "B02SMUSA9CZ",
        "type": "message",
        "text": "Incoming transmission...",
        "user": "U02SZ1TU6U8",
        "ts": "1640841349.000600",
        "team": "TP8B6LK33",
        "bot_profile": {
            "id": "B02SMUSA9CZ",
            "deleted": false,
            "name": "Mysterious Transmission",
            "updated": 1649097232,
            "app_id": "A02S6BDGHK7",
            "icons": {
                "image_36": "https:\/\/avatars.slack-edge.com\/2022-04-04\/3341079938403_76e222119bdfac66ebfe_36.jpg",
                "image_48": "https:\/\/avatars.slack-edge.com\/2022-04-04\/3341079938403_76e222119bdfac66ebfe_48.jpg",
                "image_72": "https:\/\/avatars.slack-edge.com\/2022-04-04\/3341079938403_76e222119bdfac66ebfe_72.jpg"
            },
            "team_id": "TP8B6LK33"
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "fSaFN",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Incoming transmission..."
                            }
                        ]
                    }
                ]
            }
        ]
    },
    ```

**Comment by jarommadsen** [comment]
Taking a quick peek, it looks like you're only checking for `user_profile` text blocks.

[`if (pair.ContainsKey("user_profile") && pair.ContainsKey("text"))`](https://github.com/thomasloupe/Slackord2/blob/e8a250cd5adcf1e25083c2c36724056b068e094d/Slackord_Win/Slackord/Slackord.cs#L106)

I imagine you're trying to limit some of the noise by not getting all `text` messages?

**Comment by thomasloupe** [comment]
Got it. I can add this to the list of enhancements.

I'm specifically importing messages that have a user, then I look for attachments of any kind. However, since this is a bot posting a rich text event, it's not going to get picked up. For now, the best I could possibly do is actually post the message. Later, I would look toward doing something equivalent like an embed.

**Comment by thomasloupe** [comment]
Completed: https://github.com/thomasloupe/Slackord2/commit/c1480bc9a0c6421e534fa2d0a1aeb2a10bc4178f

**Comment by jarommadsen** [comment]
This is working!

However it doesn't post the timestamp like it does with the user messages.

User messages currently are formatted like:
`<M/D/YYYY H:MM AM/PM>: <User Name>: <Message>`

Bot messages are currently formatted like:
`<Bot Name>: <Message>`

You should be able to pull off the `ts` property like you did for the `user_profile`.
