### ISSUE TITLE
User mentions are not parsed

### ISSUE THREAD

**Issue by jarommadsen** [thomasloupe/Slackord#22]
You were able to parse user names for the author of a message. Could the same be done for the `<@U123456>` mentions?

Also while I'm dreaming, do you think there's a world where you could allow manual mapping of discord user IDs to the slack user IDs so the actual mentions link to real users?

**Comment by thomasloupe** [comment]
I would need to look at how the mentions are done to see if it's feasible. Could you DM me on Twitter with a link to the JSON file for testing the potential of this enhancement?

As for mapping the Slack IDs to direct Discord user ID's I can say without hesitation that unfortunately, that is largely out of scope for Slackord2. However, you could still open the JSON file and replace a specific mention or user with technically anything! Slackord2 doesn't really care about what the user is, so you could actually just edit the JSON to be the Discord user and it _should_ work just like a real mention.

**Comment by jarommadsen** [comment]
> Slackord2 doesn't really care about what the user is, so you could actually just edit the JSON to be the Discord user and it should work just like a real mention.

Oh yeah, that's a good idea now that I've merged the JSON together.

I'll DM you now.

**Comment by thomasloupe** [comment]
User mentions are parsed.
Mapping is currently out of scope for Slackord2 but the JSON file can be modified to include appropriate discord usernames.
