### ISSUE TITLE
Parsing messages longer than 2000 characters

### ISSUE THREAD

**Issue by rehak11** [thomasloupe/Slackord#25]
Hi, 
I've tried to migrate workspace from Slack that contained multiple text messages longer than 2000 char. I thought it would be cool if Slackord could automaticly split those longer messages into multiple separate messages smaller than 2000 characters. What do you think? Whould it be possible to add such feature?
Thanks.

**Comment by thomasloupe** [comment]
Hi @rehak11, I think this is possible. I'll add it to the list of enhancements, though I have no current ETA on when this would be out.

For now, you can split that message up as an additional JSON message entry and the message will post until I can get that enhancement in.

**Comment by thomasloupe** [comment]
Completed: https://github.com/thomasloupe/Slackord2/commit/9081e723c3338bcc744e9672f7de305e85662ffb
