### ISSUE TITLE
Add Slack Thread support

### ISSUE THREAD

**Issue by thomasloupe** [thomasloupe/Slackord#26]
Currently, Slackord2 does not have thread support, so all messages are placed individually.
Support Slack threads and convert threaded conversations to Discord threads where they exist.

**Comment by jarommadsen** [comment]
What kind of help are you looking for for this?

**Comment by jarommadsen** [comment]
If it's helpful, the way that Slack threads work is they use the `thread_ts` property which is set to the parent message's `ts` property.

**Comment by thomasloupe** [comment]
Specifically, I don't have the time right now to get it done programmatically. It will be some time before I can get this implemented.

**Comment by jarommadsen** [comment]
If you write up a quick contributing guide I don't mind taking a stab at it. I'm unintimidated by the codebase although it seems that the code is duplicated per platform. Is this done programmatically or manually?

**Comment by thomasloupe** [comment]
It's no problem. It's likely I can get around to it at some point very soon.
The challenge is first knowing a message starts a thread, then placing every new comment inside of that thread.

I imagine we do a check to see if there is a timestamp for a thread, then gather all the messages up to the point where the timestamp for the thread is `null`, then foreach through them and add them to the thread. I just want to make sure I'm taking the best approach at this and want to give myself adequate time to think about the best implementation.

**Comment by thomasloupe** [comment]
I will more than likely begin work on this enhancement this weekend.

**Comment by junwoo091400** [comment]
@thomasloupe any updates? I would be interested in helping out!

**Comment by thomasloupe** [comment]
No updates currently on this.
I am still working on getting some other bugs and long-standing feature requests in. Once 2.3 is out for Linux/Mac, I can shift focus entirely toward this.

**Comment by thomasloupe** [comment]
I have begun work on this and am about halfway done through the Windows release. There are some nuances I need to work through - IE: once a thread is created, reply to the thread with additional messages, but I'm nearly finished with the enhancement, then I can move to testing.

**Comment by thomasloupe** [comment]
This feature has been completed and is now in Slackord v2.4!
https://github.com/thomasloupe/Slackord2/releases/tag/v2.4

Appreciate the support for this enhancement request!
