### ISSUE TITLE
Timestamps/headers are a bit messy

### ISSUE THREAD

**Issue by jarommadsen** [thomasloupe/Slackord#29]
Consider adding in some [markdown](https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-) to make the timestamps a bit sexier.

A couple ideas:

Idea 1:
> M/D/YYYY (quoted + new line)

**User** (bold + new line)
Message (normal + new line)

Idea 2:
**User (bold)** `M/D/YYYY (code block)`
Message (normal + new line)

Let me know what you think!

**Comment by jarommadsen** [comment]
Also maybe the ability to toggle on/off timestamps altogether.

**Comment by thomasloupe** [comment]
I had to take some time to think about this request as there is a good case for cleaning up the timestamps in general. One change was already done to improve this, but I don't disagree it can be further improved.

As of right now, I prefer to keep things inline, but there is absolutely no reason not to further clean up the timestamps with proper formatting.

Proposed method to keep things inline but replace formatting:
MM/DD/YY **User**:  Message content + `+/n`

Or proposed method to newline after User: to break up monotony of less important data:
MM/DD/YY **User**:  `+/n` Message content + `+/n`

Personally, I prefer the first method.

**Comment by jarommadsen** [comment]
My thoughts were to make it look a bit more like a regular discord message. Inline makes it a bit hard to find who it is that sent the message. Bold will help a bit.

**Comment by thomasloupe** [comment]
Okay, I'll consider this and make a decision. More than likely there's no issue with doing the latter of the two so I may just do so.

**Comment by thomasloupe** [comment]
The latest Windows release now has cleaner timestamps.
Messages are a bit more clean now, too.
See the latest Windows [release](https://github.com/thomasloupe/Slackord2/releases/tag/v2.3) (Linux/Mac coming soon).

**Comment by thomasloupe** [comment]
This feature has been completed and released for all releases of Slackord2.
See the latest release [here](https://github.com/thomasloupe/Slackord2/releases/tag/v2.3).
