### ISSUE TITLE
NullRef Exception from SlashCommand Builder

### ISSUE THREAD

**Issue by Baalzubub** [thomasloupe/Slackord#30]
Hi,

I followed the instructions:

- bot join the server (check)
- import the JSON (check)
- enter token (check)
- connect (check)

However, when I type either "!slackord" or "/slackord" it doesn't post the message. Looks like the command isn't exist.

**Comment by thomasloupe** [comment]
Hi, @Baalzubub, 
Typically, issues with posting messages into Discord are either JSON parsing related issues or connection issues. Since you've said the bot says it is connected, does the bot have access to your Discord channel? Are your messages showing they are all parsed? Which version of Slackord2 are you using and for what OS?

**Comment by mathias-lepoutre** [comment]
Hi @thomasloupe , 

I'm also experiencing an issue with similar consequence while running version v2.2.5.1 on linux.

It's all fine up to gateway connection, except that an error message is logged (see full log below): System.NullReferenceException at Discord.ApplicationCommandProperties.set_NameLocalizations(IReadOnlyDictionary`2 value), at Discord.SlashCommandBuilder.Build().
On my server the bot status is "awaiting parsing of messages", but I'm unable to execute the "/slackord" command. Meanwhile the bot is still running.

It might be related to [this recent issue](https://github.com/discord-net/Discord.Net/issues/2450) of discord.net, in which they suggest to downgrade to 3.7.2.

Here is the full log of the bot:
"
Slackord v2.2.5.1.
Created by Thomas Loupe.
Github: https://github.com/thomasloupe
Twitter: https://twitter.com/acid_rain
Website: https://thomasloupe.com

Slackord will always be free!
If you'd like to buy me a beer anyway, I won't tell you not to!
You can donate at https://www.paypal.me/thomasloupe


Found existing token file.
Reading JSON files directory...
0: Files/2021-09-26.json
[more files]
Please select a file number you wish to parse and post to Discord: 
You have the latest version, v2.2.5.1!
0
Begin parsing JSON data...

-----------------------------------------

[my file content]

-----------------------------------------

Parsing completed successfully!

Bot will now attempt to connect to the Discord server...
23:22:48 Discord     Discord.Net v3.8.0 (API v9)

23:22:48 Gateway     Connecting

23:22:49 Gateway     Connected

23:22:50 Gateway     A Ready handler has thrown an unhandled exception.:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.ApplicationCommandProperties.set_NameLocalizations(IReadOnlyDictionary`2 value)
   at Discord.SlashCommandBuilder.Build()
   at Slackord.Slackord.ClientReady() in Z:\Development\Git Repositories\Slackord2\Slackord_Mac_Linux\Slackord\Program.cs:line 316
   at Discord.EventExtensions.InvokeAsync(AsyncEvent`1 eventHandler)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)

23:22:50 Gateway     Ready
 "

**Comment by thomasloupe** [comment]
@mathias-lepoutre Thanks for the information on this.
It's very likely a bug related in the new release. If you check recent commits, you'll notice I very recently upgraded the Discord.Net lib to the latest version, away from 3.7.2. This is very likely the cause.

I'll work with Discord.Net to see when there's a fix available. If I cannot get a fix in for this or adequate information about a fix, I will revert back to 3.7.2 until the issue is resolved.

**Comment by thomasloupe** [comment]
The current dev build also does not have https://github.com/discord-net/Discord.Net/issues/2450 in the dev build release currently. I could build a new version, but instead I have inquired about a hotfix. This is actually quite a massive issue that has broken pretty much any bot that's using slash commands.

**Comment by Baalzubub** [comment]
@thomasloupe Thank you for the reply! I didn't noticed the error before but I do have the same error as @mathias-lepoutre. I'm using Slackord V2.2.5.1 with Window 10 (64-bit).

**Comment by thomasloupe** [comment]
This fix has been committed into dev now:
https://github.com/discord-net/Discord.Net/pull/2453

**Comment by thomasloupe** [comment]
Fixed in https://github.com/thomasloupe/Slackord2/releases/tag/v2.2.5.2.
Please note: This was a downgrade back to 3.7.2 until the release makes it to stable.
