### ISSUE TITLE
v2.2.5.1 Gateway Ready but not detecting /slackord command

### ISSUE THREAD

**Issue by sulliwane** [thomasloupe/Slackord#31]
Hello and thanks for the handy tool!

I created the bot, generated an invite url (checking bot AND command permissions)
![Screenshot from 2022-09-09 15-44-19](https://user-images.githubusercontent.com/1733686/189364647-69441d62-cad4-4ce5-b345-35e871d6fa38.png)

authorized the bot to join my discord server (it now appears in the users sidebar).

Then I ran the linux Slackord2 CLI app. It shows that:
![Screenshot from 2022-09-09 15-46-42](https://user-images.githubusercontent.com/1733686/189364892-9ce3f0da-c5b4-482b-ade9-42c37ec417e0.png)

Then, in #general chan, I send `/slackord`.

But nothing happen...Any idea?

Thanks for your help!

**Comment by thomasloupe** [comment]
Please see: https://github.com/thomasloupe/Slackord2/issues/30

**Comment by thomasloupe** [comment]
Fixed in https://github.com/thomasloupe/Slackord2/releases/tag/v2.2.5.2.
Please note: This was a downgrade back to 3.7.2 until the release makes it to stable.
