### ISSUE TITLE
Add a warning about private channels

### ISSUE THREAD

**Issue by xtianus** [thomasloupe/Slackord#34]
I just finished all the setup just to find out that Slack can't export private channels.
I know it's not your fault but you should add a note at the start, telling to first check the Slack export because one might not be able to get what he wants.

**Comment by thomasloupe** [comment]
You can use a great tool called [Slackdump](https://github.com/rusq/slackdump) to do that.
I may get in touch with the developer to see if they are interested in cross-linking to each other's repositories for the sake of issues like this.

**Comment by thomasloupe** [comment]
Completed. Added to README.
