### ISSUE TITLE
Add batch or multiple files in one go

### ISSUE THREAD

**Issue by wishx** [thomasloupe/Slackord#35]
Can't do more than one file at a time. The issue is that, the one linked JSON file combiner needs you to add each file manually one at a time, which is cumbersome when you have literally hundreds of JSON files per channel. The other tool I found that combines JSON files into one makes Slacklord2 error out, so it doesn't work. 

Being able to cycle through or batch all files in the FILES directory at once would be an excellent feature, marking them as done or something as they go.

**Comment by thomasloupe** [comment]
Though the readme does state why I haven't provided support for this yet, I understand the reason for requesting it. It's likely I will make this an enhancement, so I'll add it to the list of enhancements to work on.

**Comment by LukasBFreund** [comment]
@thomasloupe That would be fantastic, thank you!

**Comment by thomasloupe** [comment]
This enhancement has been completed for Windows, with Linux/Mac following shortly after.
See the latest [release](https://github.com/thomasloupe/Slackord2/releases/tag/v2.3).

**Comment by thomasloupe** [comment]
This feature has been completed for all releases of Slackord2.
See the latest release [here](https://github.com/thomasloupe/Slackord2/releases/tag/v2.3).
