### ISSUE TITLE
Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by wskidmore** [thomasloupe/Slackord#39]
Using the latest release, on windows 11, .net 7.
Have a json folder from slackdump with about 3000 json files, each having around 10-200 messages.

Executing the `/slackord` command in discord before all files have been parsed in the app you get this message:
```
Collection was modified; enumeration operation may not execute
```

Waiting for all files to be fully parsed before running the command avoids the error. For the record, the 3000 files totalled around 70MB and it took 14 hours for the app to parse.

**Comment by thomasloupe** [comment]
@wskidmore 
Got it.. hmm, that's very interesting, and a new one I haven't seen yet. Apart from downloading the source itself and giving it a good old fashioned debug, I'm not entirely sure where the operation is hanging up, but likely related also to the other issue (#37). These are currently the only two issues tracking for this release and they're pretty tough for me to track down.

For now, I would recommend downgrading to the previous release so at least you can get your messages in Discord appropriately. I may need some additional help trying to track down the problem as the test JSON I have isn't producing this issue. If you have a JSON file I can look at to reproduce the issue with, please feel free to upload it here or you can reach me on Twitter to share directly.

**Comment by thomasloupe** [comment]
Also noted your update here. I should probably not allow posting until all files have successfully parsed. Thanks for bringing that to my attention, as that's a short-sight on my part when I added folder parsing.

**Comment by wskidmore** [comment]
Its totally the parsing thing. Since the scrollbar wasnt repeatedly scrolling down to newer content and it just so happened that the line with 'xxx json finished parsing' was the last line visible in the window.

With so many json files in the folder its been parsing for about an hour now and its done maybe 2 years of messages out of 7, so im going to give it all night.

I'd close the issue.. or add the block like you said, but my vote is its user error :)

**Comment by thomasloupe** [comment]
Yeah no problem, and thanks again for bringing this to light, it's how I get fixes in 👍 
Let's leave the issue open, and when you have some time, let me know how it goes!

**Comment by thomasloupe** [comment]
Fixed for Windows:
https://github.com/thomasloupe/Slackord2/releases/tag/v2.4.3
