### ISSUE TITLE
Failed to load libhostfxr.dylib

### ISSUE THREAD

**Issue by pierrevdk** [thomasloupe/Slackord#40]
Hi,
First of all thanks a lot for what you built, that will be really useful!
I'm on Mac (Version 12.5.1) and I'm trying to launch Slackord v2.4.1 and when I do it I have this error message on the console:

> Failed to load /Users/myusername/Downloads/Slackord2_Mac_x64/libhostfxr.dylib, error: dlopen(/Users/myusername/Downloads/Slackord2_Mac_x64/libhostfxr.dylib, 0x0001): tried: '/Users/myusername/Downloads/Slackord2_Mac_x64/libhostfxr.dylib' (code signature in <15193558-3183-37F9-BD20-6CF07E31413F> '/Users/myusername/Downloads/Slackord2_Mac_x64/libhostfxr.dylib' not valid for use in process: library load disallowed by system policy)
> The library libhostfxr.dylib was found, but loading it from /Users/myusername/Downloads/Slackord2_Mac_x64/libhostfxr.dylib failed
>   - Installing .NET prerequisites might help resolve this problem.
>      https://go.microsoft.com/fwlink/?linkid=2063366
> logout
> 
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.

I have .net v7.0.0 installed and I executed the `chmod +x *` command beforehand.

Thanks by advance,

Pierre

**Comment by thomasloupe** [comment]
Hi Pierre,

Is this an M1 processor?

**Comment by pierrevdk** [comment]
Hi Thomas,Thanks for your answer. No it’s not, it’s an Intel from 2019. On 25 Nov 2022, at 16:06, Thomas Loupe ***@***.***> wrote:﻿
Hi Pierre,
Is this an M1 processor?

**Comment by thomasloupe** [comment]
@pierrevdk
Okay, I have seen another report of this recently. This may have to do with .NET7. I will need some time to investigate what is actually happening.

For now, I would recommend downgrading to the .NET6 version if you need this done sooner rather than later. This appears to be only affecting mac users.

**Comment by thomasloupe** [comment]
Hi @pierrevdk,

Could you try doing the following in terminal:
`cd /path/to/slackord2/`
`sudo xattr -r -d com.apple.quarantine *`

Then try running again and let me know if that sorts it out?

**Comment by thomasloupe** [comment]
I believe this to be resolved with the above comment.
I have updated the documentation to provide the resolution for this encountered error on mac here:
https://github.com/thomasloupe/Slackord2/wiki/Troubleshooting

If you try this and still have problems, please comment or create a new issue.
Thanks again for the report!

**Comment by pierrevdk** [comment]
It worked, thanks!

I'm just confused now, when I run Slackord, I'm not prompted to enter the token, and I don't have a Files folder inside the Slackord folder, is there something I misunderstood or I am doing wrong?

Attached the console result of the Slackord command:

> > /Users/path/to/Slackord2.4.2/Slackord ; exit;
> Slackord v2.4.2
> Created by Thomas Loupe.
> Github: https://github.com/thomasloupe
> Twitter: https://twitter.com/acid_rain
> Website: https://thomasloupe.com
> Slackord will always be free!
> If you'd like to buy me a beer anyway, I won't tell you not to!
> "You can donate at https://www.paypal.me/thomasloupe
> logout
> 
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.
> 
> [Process completed]

**Comment by thomasloupe** [comment]
I'll have a look at this. Quite odd that there's no parsing happening at all.
It appears the same is happening on Linux as well.

**Comment by thomasloupe** [comment]
Fixed now.
https://github.com/thomasloupe/Slackord2/releases/tag/v2.4.3

Octokit wasn't pulling the latest release, resulting in an error. This should be fixed now. Can you try and confirm for me?

**Comment by pierrevdk** [comment]
You are awesome @thomasloupe!
It worked, I was able to add the bot's token, but I don't see a Files folder inside the Slackord2 folder. I've created one, added some json files inside but I keep having this:

> Slackord v2.4.2.1
> Created by Thomas Loupe.
> Github: https://github.com/thomasloupe
> Twitter: https://twitter.com/acid_rain
> Website: https://thomasloupe.com
> 
> Slackord will always be free!
> If you'd like to buy me a beer anyway, I won't tell you not to!
> You can donate at https://www.paypal.me/thomasloupe
> You are running an outdated version of Slackord!
> Current Version: v2.4.2.1
> Latest Version: v2.4.3
> You can download the latest version at https://github.com/thomasloupe/Slackord2/releases/tag/v2.4.3
> 
> Found existing token file.
> Reading JSON files directory...
> You haven't placed any JSON files in the Files folder.
> "Please place your JSON files in the Files folder then press ENTER to continue.

What should I do differently?

**Comment by thomasloupe** [comment]
You're very welcome.
Could you try chmod'ing Slackord for read/write/execute permissions?

`cd path/to/slackord/`
`chmod +rwe *`
`chmod +rwe Slackord`

**Comment by pierrevdk** [comment]
I've tried it, console answers: `chmod: Invalid file mode: +rwe`

**Comment by pierrevdk** [comment]
It actually worked by re-running `chmod +x *` with the Files folder I created.

**Comment by thomasloupe** [comment]
Really glad to hear that!
I will create an enhancement to include the folder instead of creating it so we don't run into issues for Linux and Mac.

Are we good to close this off?

**Comment by pierrevdk** [comment]
Sorry, yes you can, thanks a lot for your help @thomasloupe!

**Comment by thomasloupe** [comment]
Awesome, glad to help!
