### ISSUE TITLE
Can't import channels

### ISSUE THREAD

**Issue by lebik** [thomasloupe/Slackord#41]
<img width="340" alt="image" src="https://user-images.githubusercontent.com/15812611/206899567-15c2e1d5-367c-47ab-a1b3-e941a7fb6c15.png">

**Comment by thomasloupe** [comment]
It looks like you didn't place a `channels.json` file inside the Files folder.
Was this done and is it named channels.json?

**Comment by thomasloupe** [comment]
Just checking in on this once again to see if you have placed a channels.json file within your `Files` folder.
I will close this issue due to inactivity by Friday if there is no response.
