### ISSUE TITLE
Thread messages can be posted to the wrong place

### ISSUE THREAD

**Issue by ben-reilly** [thomasloupe/Slackord#42]
**Windows v2.4.3**

I've been using this tool to help some friends and me move our Slack instance to Discord. Unfortunately, there are some major problems with message threads.

Here are two that I have found so far:
1. Sometimes messages that should be in threads are posted as channel messages, and
2. Thread messages are posted to the most recently created thread, even if they are supposed to belong to some earlier thread.

For the first one, I had a look at the code and it appears that the cause is that you have three separate arrays that are meant to be the same size: one for messages, and two for boolean flags that are meant to be associated with those messages. However, these arrays do not end up being the same size, as you add other things into the messages array without adding to the other two.

For the second, I believe the root cause is that you are only storing whether a message belongs to a thread, and not which thread it belongs to. Whenever a thread message is posted, it simply takes the last thread ID, which is often incorrect.

**Comment by thomasloupe** [comment]
Yes, that's correct.
The booleans should determine whether or not that message is a part of a thread or not.
When messages are posted as threads, typically the JSON should show the thread start, then thread replies. It's possible that the JSON has a thread reply later after some other message and this might be messing things up.

Would you happen to have a sample bit of JSON I could look at where it didn't post correctly so I can verify this?

**Comment by thomasloupe** [comment]
I was unable to reproduce this issue with quite a few JSON tests I created, but there have been a few updates since then. I would encourage you to share a problematic JSON file if possible.

Will close as unable to reproduce in a few days if there's no response.
