### ISSUE TITLE
Threat detection while downloading!

### ISSUE THREAD

**Issue by assoscoupa** [thomasloupe/Slackord#43]
During the process of downloading the installation file for Windows v2.4.3.2, the following threat was detected by Bitdefender Total Security:

**Gen:Variant.Lazy.276538**

Can you check the file again?

**Comment by thomasloupe** [comment]
Hi @assoscoupa,

This is clearly a false positive with BitDefender.
Apart from using Octokit and Discord.NET there aren't any third-party packages being used.
I'll submit a false positive report to BitDefender, and I'd recommend you do the same. It's impossible for me to submit every new version to every antivirus/malware suite, but I can at least submit the report for this one.

**Comment by thomasloupe** [comment]
Could you please either upload a screenshot of the threat window showing the name and/or upload it here.
I would appreciate if you could upload it to https://www.bitdefender.com/consumer/support/answer/29358/ along with the screenshot.

**Comment by thomasloupe** [comment]
Current tickets:
1008002861
1008002870

**Comment by assoscoupa** [comment]
This is the warning message from bitdefender.
![Screenshot 2022-12-27 09 14 35](https://user-images.githubusercontent.com/11008902/209627807-5a5b3f47-52ce-4def-ad72-bc7692686404.png)

**Comment by thomasloupe** [comment]
Hello @assoscoupa, it doesn't appear Bitdefender ever got back to me about either of the tickets.
Could you please try the software again and let me know if you continue to see this?

**Comment by thomasloupe** [comment]
Hi @assoscoupa,

I've not heard back from you about this, so I will proceed to close the issue off by this weekend.
