### ISSUE TITLE
Error reading JArray from JsonReader. Current JsonReader item is not an array

### ISSUE THREAD

**Issue by AddictionRecovery** [thomasloupe/Slackord#46]
I'm trying to get Slackord2 working and I'm testing with a single channel export which I generated using Slackdump. I have the JSON file in the correct folder and Slackord2 detects it, but when it tries to parse it I get about 100 of the following error before it finally quits:

Reading JSON files directory...
Found 1 files in the Files folder.
Error reading JArray from JsonReader. Current JsonReader item is not an array: StartObject. Path '', line 1, position 1.
An error occured while parsing the JSON file. Please try again.

I'm not sure why because the .json file I generated with Slackdump begins with an array. I created a new one with just a single message for privacy reasons which I've uploaded here as a .zip file. Can you take a look at this and see if you spot a reason why Slackord2 keeps throwing parsing error? Thank you so much in advance for any help you can offer here.  

[C04LZKN28EP.json.zip](https://github.com/thomasloupe/Slackord2/files/10527988/C04LZKN28EP.json.zip)

Update: I also tried using the original Slackord and when I try my file there I get: "Slackord will post the following 0 messages (plus thread contents if applicable) to your desired Discord channel:" so it really just doesn't like this file but I'm still not sure why given that it seems to be perfectly valid JSON.

**Comment by thomasloupe** [comment]
Hi @AddictionRecovery,

I had a quick look at your JSON.
A typical JSON file for Slack would look like:
```
[
    {
        "client_msg_id": "7a369f56-c62a-46d3-ae09-355e8efd87e9",
        "type": "message",
        "text": "wowweee",
        "user": "U02T1PW6WP8",
        "ts": "1659256839.295139",
        "team": "T02T5GR2G05",
        "user_team": "T02T5GR2G05",
        "source_team": "T02T5GR2G05",
        "user_profile": {
            "avatar_hash": "9eae025fd965",
            "image_72": "https:\/\/avatars.slack-edge.com\/2022-01-09\/2939137590481_9eae025fd965ab926236_72.jpg",
            "first_name": "Thomas",
            "real_name": "Thomas Loupe",
            "display_name": "",
            "team": "T02T5GR2G05",
            "name": "acidxrain",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "HA6h",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "wowweee"
                            }
                        ]
                    }
                ]
            }
        ]
    },
```

Your JSON looks like:
```
{
  "name": "testing",
  "messages": [
    {
      "type": "message",
      "user": "U94BU0DNU",
      "text": "\u003c@U94BU0DNU\u003e has joined the channel",
      "ts": "1674930843.942409",
      "subtype": "channel_join",
      "replace_original": false,
      "delete_original": false,
      "metadata": {
        "event_type": "",
        "event_payload": null
      },
      "blocks": null
    },
    {
      "client_msg_id": "a6cc5859-81d9-48c3-a90d-d28ee71c8e91",
      "type": "message",
      "user": "U94BU0DNU",
      "text": "Starting with just a single message",
      "ts": "1674930859.492469",
      "team": "T5YGW7T7T",
      "replace_original": false,
      "delete_original": false,
      "metadata": {
        "event_type": "",
        "event_payload": null
      },
      "blocks": [
        {
          "type": "rich_text",
          "block_id": "EPvL3",
          "elements": [
            {
              "type": "rich_text_section",
              "elements": [
                {
                  "type": "text",
                  "text": "Starting with just a single message"
                }
              ]
            }
          ]
        }
      ]
    }
  ],
```
Note that mine opens up as an array, and yours does not.
`[` = array
`{` = dict
My formatting: `[{}]`
Your formatting `{}`
To put it clearly, you're missing the array that starts the file, and that's resulting in `Current JsonReader item is not an array: StartObject. Path '', line 1, position 1.` where Slackord is telling you it's expecting an array first. You could try to wrap it around an array and see what that does.

**Comment by AddictionRecovery** [comment]
@thomasloupe Well I clearly have not had enough coffee this morning. You are 100% right I can't believe I didn't see that it wasn't actually wrapped in an array... as soon as I did Slackord2 was able to parse my test file. Thank you SO much for the help and sorry for not realizing this beforehand.
