### ISSUE TITLE
Reset token file/re-add bot token

### ISSUE THREAD

**Issue by AddictionRecovery** [thomasloupe/Slackord#47]
I'm so incredibly sorry for such a fast second issue ticket but I can't figure out how to change the discord bot token. I had it open in a new document but my text editor crashed and I wasn't able to save it so I had to re-generate the bot token. However every time I execute Slackord2 it says "Found existing token file." and I don't have an option to replace/reset it. 

How can I do this?

**Comment by thomasloupe** [comment]
I'm assuming you're using the Mac or Linux version of Slackord, so you should see a text file in the main directory called `Token.txt`. You can change the token there directly. If there isn't one, you can recreate it and give it execute permissions.

**Comment by AddictionRecovery** [comment]
@thomasloupe Thank you, that took care of it. Unfortunately I have a final issue which I'll make a separate report for. Closing this one.
