### ISSUE TITLE
Error in discord when trying to import messages: The application did not respond

### ISSUE THREAD

**Issue by AddictionRecovery** [thomasloupe/Slackord#48]
Now that my initial issues have been resolved I went to do my first test import and unfortunately it did not go as expected. I ran the /slackord command in the test channel I wanted to try this import to and the bot simply responded with: "The application did not respond"

However, in my terminal running Slackord2 I got the followiong:

`Beginning transfer of Slack messages to Discord...
-----------------------------------------
-----------------------------------------
All messages sent to Discord successfully!`

So Slackord2 thinks there was a successful import when there wasn't one. Thank you in advance again for any help you can provide.

**Comment by thomasloupe** [comment]
Were there messages that parsed when you first imported the JSON file?
It's likely that you need to switch to a Slack export instead of a Slackdump export and test that way.

**Comment by AddictionRecovery** [comment]
@thomasloupe Actually no you're right after watching the example video again it did not display any messages in the terminal. Can you be more specific when you say I need to switch to a slack export instead of a slackdump export?  Update: nevermind found the docs here https://github.com/rusq/slackdump/blob/master/doc/usage-export.rst I'll give that a try and see how it goes. Thank you!!

**Comment by AddictionRecovery** [comment]
@thomasloupe Thank you SO much, exporting using the other method resulted in messages after parsing and I was able to complete my test import. I think I have everything I need now, thank you!!

**Comment by thomasloupe** [comment]
No problem at all! If you're happy with everything, feel free to close this issue out!

**Comment by thomasloupe** [comment]
Closing this as resolved.
