### ISSUE TITLE
Is there a way to map users?

### ISSUE THREAD

**Issue by AddictionRecovery** [thomasloupe/Slackord#49]
The tool works great, but it would be really nice if the imported chat history could be associated with corresponding users on Discord. For example:

[
{"slack":{"id":"U94BU0DNU"},"discord":{"name":"Tyler Cunningham#7064", "id":"1044822873405149256"}}
]

Does Slackord2 allow for any kind of user mapping?

**Comment by thomasloupe** [comment]
Well, the short answer is no.
The long answer is, Slackord can only speak on its own behalf, so the absolute best it could do if supported as a feature is put the @ tag and tag the user that said the line.

This causes massive amounts of spam to users, but also, it's just not very clean. 

However, I could consider adding that if the names are already pre-mapped via JSON. Does slackdump do this? If so I could just plaintext the name without a mention.
