### ISSUE TITLE
Multiple directory imports requires a restart of Slackord on Win

### ISSUE THREAD

**Issue by damonseeley** [thomasloupe/Slackord#53]
Slackcord2 2.4.6 on Win10

FYI

I find that after a successful import of a whole directory of JSON files if I try again for another channel Slackcord2 will only import the first JSON file it finds. 

The fix is easy disconnect and restart Slackcord2.exe and then it works again.

**Comment by thomasloupe** [comment]
Is this only happening for folder imports, not single files?
Both [here ](https://github.com/thomasloupe/Slackord2/blob/07471533be732ba13b2ed5857afa63801f1b1db4/Slackord_Win/Slackord/Slackord.cs#L710) and [here](https://github.com/thomasloupe/Slackord2/blob/07471533be732ba13b2ed5857afa63801f1b1db4/Slackord_Win/Slackord/Slackord.cs#L719) I am clearing the list of files added any time the button to load a JSON file is cleared, and it should re-read the full structure as it does the first time so this is very odd.

**Comment by damonseeley** [comment]
Yeah only after Folder imports. Happens pretty consistently.

**Comment by thomasloupe** [comment]
Could you try this again on the [latest release](https://github.com/thomasloupe/Slackord2/releases/tag/v2.4.9) and let me know if you still have this problem? Thank you!

**Comment by damonseeley** [comment]
Hmm, on second run I get an immediate "A SlashCommandExecuted handler is blocking the gateway task."

Error: If I cancel the Discord command and then disconnect and reconnect from Slackcord it first appears to work but then shows that it's posting the JSON from an earlier scan of a directory. So not working.

**Comment by thomasloupe** [comment]
Got it. This is good info. Might be able to hotfix. The gateway task usually just means it's either not ready yet or that it's rate limited but could also be a problem.

**Comment by damonseeley** [comment]
Honestly this is not a super big deal. It's OK for my workflow to just restart for each channel

**Comment by thomasloupe** [comment]
No problem, you can do the workaround, but I will leave this bug open and continue to work on it.

**Comment by thomasloupe** [comment]
If you can, can you please summarize the issue as it is now so I'm tracking down the right problem(s)?

**Comment by damonseeley** [comment]
Yep totally. Lemme re-run and get back to you

**Comment by thomasloupe** [comment]
How did this go?

**Comment by thomasloupe** [comment]
I am resolving this in the upcoming major release of Slackord.

**Comment by thomasloupe** [comment]
Fixed in [Slackord 3.0.0.](https://github.com/thomasloupe/Slackord/releases/tag/v3.0.0)!
