### ISSUE TITLE
Non-threaded posts are appearing as threads

### ISSUE THREAD

**Issue by damonseeley** [thomasloupe/Slackord#54]
During a JSON directory import the final 3 files were appended as a thread to the channel I was importing into, despite not being threaded conversations in Slack.

Idea: The posts in these files also happen to be the only ones with images attached, so that could be a clue.

Happy to provide sample data via DM

**Comment by thomasloupe** [comment]
Sure, please upload a sample to drive or somewhere else with the last _four_ files (including the one prior that made the initial thread) and I can have a look into it. It's likely I may not get a fix out tonight for it.

You can DM this to me on Twitter or some other means if it needs to be private.

**Comment by damonseeley** [comment]
OK I tried again with just a few files and it does not happen. Weird.

Sending you files via DM

**Comment by thomasloupe** [comment]
Yes, I think this might be because of how I'm resetting the list of files. I'll definitely have a look into that.
Thanks for all the reports and the support. It helps greatly with making Slackord better!

**Comment by damonseeley** [comment]
Seems to be fixed

**Comment by thomasloupe** [comment]
Awesome! Will go ahead and mark this one resolved!
