### ISSUE TITLE
Slackcord2 never finishes parsing JSON folder data

### ISSUE THREAD

**Issue by damonseeley** [thomasloupe/Slackord#57]
2.4.8 Win 10

When importing a JSON folder the operation does not complete. The app reports "Begin parsing JSON data..." and when the Discord bot tries to connect the app throws a dialog saying "Slackord is currently parsing one or more JSON files. Please wait......"

**Comment by thomasloupe** [comment]
Okay, do you know which file it's happening on? Is it the first one?

**Comment by thomasloupe** [comment]
`Exception thrown: 'System.IO.DirectoryNotFoundException' in System.Private.CoreLib.dll`

**Comment by thomasloupe** [comment]
Oops, I've found the problem!
It appears I goofed and added some linux code to the Windows release.

```
            var directoryPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Files"); // combine app's directory path with "Files" folder name
            ListOfFilesToParse = Directory.GetFiles(directoryPath, "*.json")
                                 .OrderBy(file => DateTime.ParseExact(Path.GetFileNameWithoutExtension(file), "yyyy-MM-dd", CultureInfo.InvariantCulture))
                                 .ToList();
```

It's expected a "Files" folder like Linux. Working on a solution now.

**Comment by thomasloupe** [comment]
In addition to the above issue, there was another issue with the sample you provided, where some files had "hidden_by_limit" as their values, which means there actually wasn't a file to post. In cases like this, Slackord would have failed, but instead, I've handled the error and skip over the file since there's nothing to attach or add. I'm pushing this hotfix release out now, which should fix your issues.

**Comment by thomasloupe** [comment]
This should now be fixed. Please confirm for me when you are able to!
https://github.com/thomasloupe/Slackord2/releases/tag/v2.4.8.1

**Comment by thomasloupe** [comment]
Channel importing is now fixed in:
https://github.com/thomasloupe/Slackord2/releases/tag/v2.4.8.2

**Comment by damonseeley** [comment]
Win 2.4.8.2

OK, it appears to be parsing directories . 

Two new issues, though:
1. It's parsing out of order again
2. It seems to be operating much more slowly now. It parses several files and then waits a bit, then parses more. The 166 files that took just a few seconds last time now takes many minutes of waiting.

**Comment by damonseeley** [comment]
I tried again, this time without being connected to the bot. It goes faster, but then I hit this error:

![Screenshot 2023-04-01 211458](https://user-images.githubusercontent.com/6028159/229331018-51ca292c-ab27-4093-b1a2-e3a2b05279c1.png)

**Comment by damonseeley** [comment]
Example of order
![Screenshot 2023-04-01 211651](https://user-images.githubusercontent.com/6028159/229331106-48d489f5-6096-4f4b-9d7d-9222f01db6e0.png)

**Comment by thomasloupe** [comment]
We can fix the out of order issue, but we need to figure out which file it is that's causing the issue with files at this point.
That error message is a null reference to one of your file attachments. Were you able to figure out which file this came from, and additionally, did this error message pop up multiple times that you had to click "OK" for?

**Comment by thomasloupe** [comment]
Can you please resend the export over to me via Twitter?
I'll try and work through this tonight and tomorrow.

**Comment by thomasloupe** [comment]
I believe I've fixed this issue in the [latest release](https://github.com/thomasloupe/Slackord2/releases/tag/v2.4.9). Could you please try it when you have a chance and let me know how it goes? Thanks!

**Comment by damonseeley** [comment]
OK - so close! It worked, and was in order, but it left the last two JSON files out, or did not post them.

**Comment by thomasloupe** [comment]
Can you resend me the JSON over Twitter so I can test that again? I'm sure I can probably work it out.

**Comment by damonseeley** [comment]
Will do. I'm testing again with a clean run.

**Comment by damonseeley** [comment]
OK i tried again. It seems to work but I'm now getting a repeat of the error where it fails to post the final few messages. It's not a file-based thing, but just the messages.

**Comment by thomasloupe** [comment]
Okay, got it.
I think I may have seen this during testing. I am not sure why that is happening, but I think it may be related to parsing the JSON in a specific order. I'll have a look.

**Comment by thomasloupe** [comment]
Okay! I think I was able to reproduce the error. It's related to processing file contents where some file objects were null.
I've now been able to process all messages to 2023-03-07.json from your export successfully as far as I can tell.
The [latest release](https://github.com/thomasloupe/Slackord2/releases/tag/v2.4.9.1) should now fix this.

**Comment by SELF-HQ** [comment]
Not sure if my issue is related to the above....option 2 in Mac terminal produces this result: 

Selection: 2
Not a valid option...
String 'integration_logs' was not recognized as a valid DateTime.

--

It's weird as option 1 worked fine and all the channels imported. The integration json date format is: "date":"1673902003"

Not sure what to change that to.

**Comment by thomasloupe** [comment]
This is a different bug, can you open a new issue and provide a JSON file and I can have a look now.

**Comment by thomasloupe** [comment]
Closing this one as completed.
