### ISSUE TITLE
sysout stutters when showing parsed entries

### ISSUE THREAD

**Issue by Geczy** [thomasloupe/Slackord#6]
The tool tries to scroll to the bottom but keeps jerking back to the top, and this is repeated endlessly

Perhaps it's only an issue with large json file? I'm trying 8 months of data in one go

Likely a fallout from #2

**Comment by thomasloupe** [comment]
Hey @Geczy,

Yeah, I did notice this with large JSON entries. This is not a problem for smaller entries. The larger entries _will_ still parse, but it will take **_significantly_** (as in multiple minutes) longer, and the output log will show the same messages scrolling. I'm looking into that, but not sure if it's just something that happens based on how large the JSON file-size is.

Eventually, you will begin to see the full output being parsed, but it takes a ridiculously long time. It appears there's a lot of garbage collection going on, so I need to clean this up and make it more effective for bigger entries.

Thanks for confirming the bug.

**Comment by Geczy** [comment]
I think if it's a large JSON, that it's better to not output anything to stdin. Rather, show a progress bar

I bet that would even speed up parsing

**Comment by thomasloupe** [comment]
Are you able to provide a test JSON file for me? I'd like to have a look at this now. You can DM me the JSON via Twitter if you'd like.

**Comment by thomasloupe** [comment]
I wasn't able to reproduce this with the JSON files I have. No other JSON files provided to test with.
