### ISSUE TITLE
Import issues: messages skipped and some URLs duplicated

### ISSUE THREAD

**Issue by 8bitgentleman** [thomasloupe/Slackord#60]
Running into a few more small issues:

1. Sometimes when an old message included both text and an attachment Slack hides the attachment link from the slack export (if the user has a non-paying account). Slackord skips those attachments but unfortunately also skips the text only portion of the message.
2. Sometimes Slackord doesn't handle rich-text elements correctly. Sometimes a link is imported with duplicated text, making it unusable
<img width="614" alt="Screenshot 2023-04-02 at 9 31 01 AM" src="https://user-images.githubusercontent.com/4028391/229356049-4be1d0ea-2587-45e2-ab01-4b9201d9f68b.png">

**Comment by thomasloupe** [comment]
This should now be fixed in the [latest release](https://github.com/thomasloupe/Slackord2/releases/tag/v2.4.9). Thanks for all the reports!

**Comment by thomasloupe** [comment]
Closing this one as completed now.
