### ISSUE TITLE
Bot should delete the !slackcord message after posting the parsed JSON.

### ISSUE THREAD

**Issue by Drexl** [thomasloupe/Slackord#7]
A minor QOL improvement that would make me very happy. I don't want to delete it each time. I'll have made a significant dent in the many hundreds of JSONs I'm about to import before this happens probably, but maybe it'll help someone in the future.

**Comment by thomasloupe** [comment]
The bot would have to be a moderator in your chat, and I'd need to code cases where it is and it isn't. That's a lot of work for one request. I will consider it though, and if it's something that I think I can do relatively easily, I'll implement it.

**Comment by Drexl** [comment]
I'm largely ignorant to how the API for discord works. For what it's worth I requested something similar for another (completely unrelated) discord bot. The author decided to do it, but only because it didn't require additional permissions.

https://github.com/0xz00n/EDPriceCheckBot/issues/1

I'm not sure if that will be helpful at all, but that's the extent of the contributions I can make.

**Comment by Drexl** [comment]
Fair point. I was thinking of a similar situation that came up with another bot, but in that case it only had to delete it's own messages. I can see how that might be more involved. Hopefully it's an easy enhancement.

**Comment by thomasloupe** [comment]
Yeah, so, I've given this quite a bit of thought and I don't think this is something I want to implement. The bot will absolutely have to have moderator privileges and I don't think that's something I wanna do at this time. I considered having it check what privileges it has and then add a setting to remove the command triggers automatically, but that would require me to build the bot in two different ways and have the user decide which role they've assigned the bot. I don't see that being intuitive at all so I'm deciding at this time not to implement this one.

In the meantime, it may be best to use the search feature in the channel you sent the command trigger to for "!slackord". You can just delete those pretty quickly. I know that's not what you're really after, but just an idea!
