### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by robertsLando** [thomasloupe/Slackord#76]
Why does latest version doesn't have a linux build?

**Comment by thomasloupe** [comment]
Hi @robertsLando 
.NET MAUI doesn't support Linux.

**Comment by thomasloupe** [comment]
I am, however, keeping an eye on when/if support for Linux does release for .NET MAUI, and if support does come for it, there will be very little, to no change at all, needed to deploy for Linux.

**Comment by robertsLando** [comment]
Ok thanks for the information!
