### ISSUE TITLE
Mac 3.0.0 release contains invalid application

### ISSUE THREAD

**Issue by kylev** [thomasloupe/Slackord#78]
**Slackord version (please complete the following information):**
 - OS: Mac
 - Version: 3.0.0

**Describe the bug**
Mac app incorrectly packaged and cannot be executed.

**To Reproduce**
1. Download and unzip the [Mac release](https://github.com/thomasloupe/Slackord/releases/download/v3.0.0/Slackord_Mac_x64.zip).
2. Attempt to run or double-click the Slacklord.app folder in Finder.
3. Receive error about improper packaging.

**Screenshots/Videos, etc**
<img width="276" alt="image" src="https://github.com/thomasloupe/Slackord/assets/46888/151392dc-999f-4981-9815-e220304584df">

**Additional context**
There also seems to be a ton off non-MacOS files like Windows `.dll` included in the root of the release `.zip`.
<img width="832" alt="image" src="https://github.com/thomasloupe/Slackord/assets/46888/c3594221-36d3-47bf-8fb4-9fa6e5a5f053">

**Comment by thomasloupe** [comment]
Hi @kylev,

Thanks for the report!
I'm aware of this issue and am actively working to resolve it. 3.0.1 should result from that as soon as I've resolved.
In the meantime, you can use the previous release for Mac, albeit, a lot more tedious, if need be.

**Comment by abrichr** [comment]
Any update on this? 🙏

**Comment by thomasloupe** [comment]
Hi everyone,

I am still actively trying to find a solution for this. It appears the mac build just doesn't work on mac, regardless of how I build it. 🤷‍♂️ 
This is something I could probably use some additional support with, as it appears the C# community hasn't been able to assist with the issue. Please feel free to clone the repo and see if you're able to build it for mac. I've got a testbed mac here and get the same errors.

**Comment by thomasloupe** [comment]
This issue has been fixed in 3.0.2. All future releases should have a working Mac version now!
