### ISSUE TITLE
Pipe characters in hyperlinks are formatted incorrectly

### ISSUE THREAD

**Issue by FrenkLoonen** [thomasloupe/Slackord#79]
**Slackord version (please complete the following information):**
 - OS: Windows
 - Version: 3.0.1

**Describe the bug**
Pipe characters in hyperlinks are sometimes formatted incorrectly. In my exports I see two ways of formatting hyperlinks:
<http://someurl.com/>
<http://someurl.com|someurl.com>

I think the bottom one is because of custom hyperlink formatting (often when people want to share a lengthy link, they will give it the name "link" or something). But Discord doesn't support custom hyperlinks (other than using the cumbersome web hooks or bots). The way the second link now ends up in the imported messages is as http://someurl.com%7Csomeurl.com/ which is ugly and annoying.

**To Reproduce**
1. Select JSON folder
2. Type /slackord
3. See error

**Screenshots/Videos, etc**
Sent in the ticket in Discord

**Additional context**
None

**Comment by thomasloupe** [comment]
Fixed in [3.0.2](https://github.com/thomasloupe/Slackord/releases/tag/v3.0.2).
