### ISSUE TITLE
repeated messages, possibly a result of the parser not handling threads properly. 

### ISSUE THREAD

**Issue by Drexl** [thomasloupe/Slackord#8]
We're getting A TON of repeated messages. My guess based on my observations so far is that any message that was broken out into a thread is having the root message repeated for each thread response and the threads themselves are being lost. This is a pretty serious problem if true.
I could be speaking completely out of ignorance though, so please correct me if so.

**Comment by thomasloupe** [comment]
Are you able to email me the JSON file by chance to thomasgloupe@gmail.com? I'd like to take a look. Slackord wasn't really meant for threads as much as it was for messages but I'm sure there's something that can be done if I have a file to look at to see how it's posting. Thanks!

**Comment by Drexl** [comment]
I'll see if I can find a suitable sample that is permissible to share.

**Comment by Drexl** [comment]
My apologies. My conclusion was a bit premature. It appears the real reason was a small issue with a script we were using to combine the JSONs, as well as some other string manipulation we needed to perform. This issue is solved. :)
