### ISSUE TITLE
Empty threads and/or threads containing messages that don't belong in that thread

### ISSUE THREAD

**Issue by FrenkLoonen** [thomasloupe/Slackord#81]
**Slackord version:**
 - OS: Windows
 - Version: 3.0.1

**Describe the bug**
In some cases, empty threads get created. In other cases, threads can contain messages that don't belong in that thread.

**To Reproduce**
1. Select JSON folder
2. Type /slackord
3. See threads created
4. Compare with screenshots from Slack

**Screenshots/Videos, etc**
See Discord ticket 8.

**Comment by thomasloupe** [comment]
This is now fixed in 3.0.3.
