### ISSUE TITLE
Support Importing More Than 50 Channels At Once

### ISSUE THREAD

**Issue by ElioDiNino** [thomasloupe/Slackord#86]
**Is your feature request related to a problem? Please describe.**
When your Slack import consists of more than 50 channels, an error occurs since Discord only supports a maximum of 50 channels per category.

**Describe the solution you'd like**
Slackord should produce more categories when needed.

**Describe alternatives you've considered**
This can be avoided by performing the imports in waves, but it is more work.

**Additional context**
![image](https://github.com/thomasloupe/Slackord/assets/52972357/2267bfc4-00d2-4517-8edb-2364f5716a2f)

**Comment by thomasloupe** [comment]
Added in [4.0.1](https://github.com/thomasloupe/Slackord/releases/tag/v4.0.1).
