### ISSUE TITLE
Button to toggle between full names or display/user names

### ISSUE THREAD

**Issue by FrenkLoonen** [thomasloupe/Slackord#89]
As a workspace admin in Slack, you get to check whether you want full names to show:

```
**Name Display**
If you’d like, Slack can show your members’ full names instead of their shorter display names.

[ ] Show full names instead of display names
```
Currently in Slackord, the order of the names being displayed next to imported messages is the following (I think):
- display name
- username
- real name

I get that from a privacy perspective, you choose username over real name. But a username is always populated (I'm guessing) whereas a display name often isn't, so it never gets to the real name. Therefore, I would like to have a button to prioritize real name over username (which basically resembles our current Slack workspace setting).

So:
"Show real name" set to True:
1. display name
2. real name
3. username

"Show real name" set to False:
1. display name
2. username

**Comment by thomasloupe** [comment]
This enhancement is marked for the next major release of Slackord.
The current intention is to create a button similar to the `Timestamp` toggle, where we will toggle between the following options:

`display name` > `username` > `real name`
`username` > `display name` > `real name`
`real name` > `username` > `display name`

Format is based on an Enum type.
When the value is an empty string, we will fall back to the next in the order.

@FrenkLoonen What do you think about this?

I do not think I want to set this up in a way that allows users to set that order up, as I prefer to lean into the privacy-first approach.

**Comment by FrenkLoonen** [comment]
@thomasloupe  the way I see it, is that in Slack, privacy is slighty less of a thing than in Discord, since in Slack a user's email address is always visible anyway, and you have to specify your real name when signing up for Slack (even though you can probably just provide whatever text you like).

In my case, I'm migrating a community of professionals in which everyone is eachother's first or second connection. So almost everyone knows eachother by their own names, not nicknames like you would have in a gaming or crypto community. And for this reason, I'm actually also considering strongly suggesting (I don't want to actually go and force people) to use their full name in their Discord profile. We mitigate the privacy issue by making sure that we only allow people to join our server after vetting them. No one gets to invite strangers by themselves.

I'm looking at my users.json right now. Name (or username in your example) is always the first part of the email address a person signed up with, so it is never empty. A real name is mandatory when signing up for Slack and a display name is optional. I see a lot of users who leave it empty (they are fine with having their real name shown), a lot of users who just repeat their real name as their display name, and a handful of users who only specified their first name as a display name, 

Therefore, my preferred order would be:
1. Display name (after all, that is the name a user has deliberately chosen to be displayed)
2. Real name (with a toggle to not include real name altogether)
3. Username

So you'd only need a toggle for including real names yes or no, imo.

**Comment by thomasloupe** [comment]
This has been added to version 4.3.0 which is now available on the beta branch.
