### ISSUE TITLE
Slackord not detecting message JSON from slackdump

### ISSUE THREAD

**Issue by frankpinto** [thomasloupe/Slackord#90]
**Slackord version (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: 22621.2428

**Describe the bug**
I have a 14310 line JSON file with Slack messages from a single channel exported using slackdump. When selecting the folder using "Import JSON" it doesn't detect a JSON file in that folder at all

**Comment by thomasloupe** [comment]
There are quite a few issues with using Slackdump exports at the moment. My current recommendation at the time would be to export directly from Slack and use that. There may still be errors, but my current focus right now is specifically on getting Slackord to successfully import Slack exports, then move to Slackdump and provide support there.

If you can, try the regular Slack export, then if you still run into issues, please feel free to join the community Discord and we can walk through it.

**Comment by thomasloupe** [comment]
I will be removing support for Slackdump after quite a few issues have come up in the past few months. It appears Slackord has become less and less compatible with Slackdump over time. It's difficult for me to continue support Slackdump fully when the common exports are one format, and Slackdump JSON dumps can start with `{` or `[`. I would need to convert each Slackdump programmatically, which is out of the scope for Slackord.

Apologies for this, as I know it's not great news. You can still import a default Slack export, and it should work fine.
I will update the readme in the coming days to remove official support. I am still available via our Discord community if you still need assistance. I will do the best I can to help!
