### ISSUE TITLE
How to build and use for Mac

### ISSUE THREAD

**Issue by syedzainqadri** [thomasloupe/Slackord#92]
Hi, 
Can you guide on how can we use this as a Mac based software the older version does run on Mac but it does nothing when clicked on import Jason. 

If you can guide me how to use it on Mac it will be great help

**Comment by thomasloupe** [comment]
Mac release is currently broken. I'm trying to get a fix done, but there are no guarantees that I can get it working as the issue is related completely to a .NET+MAUI issue with HttpClient.

**Comment by thomasloupe** [comment]
You can now download and use the mac version in the latest release.

**Comment by syedzainqadri** [comment]
Why dont we just change the language to something more adaptable like flutter if it is all abt httpclient dart can be a reasonable alternative in building cross platform solution like this one.

**Comment by thomasloupe** [comment]
The issue has been fixed with httpclient, so there's no need to change the language. You can use the Mac version right now.
