### ISSUE TITLE
when I try to import the json, it just says "no users found in users.json file" and quits trying to import

### ISSUE THREAD

**Issue by loversandlasers** [thomasloupe/Slackord#93]
**Slackord version (please complete the following information):**
 - OS: Mac
 - Version: 14.3

**Describe the bug**
When I select a channel folder and click import, it just says, "No users found in users.json file," and quits trying to import. I've tried copying and pasting the users.json file into the channel folder, and all it does is "parse the users," but it does not pull in any of the messages. I've tried selecting the folder containing all channels and messages, and the program crashes. 

**To Reproduce**
1.  Click "Import JSON"
2. Select the channel JSON folder (it doesn't matter which one)
3. See the error "No users found in users.json file"

<img width="533" alt="Screenshot 2024-01-24 at 11 43 01 AM" src="https://github.com/thomasloupe/Slackord/assets/157636771/7735748c-0b44-4df2-bd90-2fb9bdf013d9">
<img width="1026" alt="Screenshot 2024-01-24 at 11 43 36 AM" src="https://github.com/thomasloupe/Slackord/assets/157636771/7fb1f5ca-d005-4ea3-8afc-2badd1a321d2">
<img width="1025" alt="Screenshot 2024-01-24 at 11 44 10 AM" src="https://github.com/thomasloupe/Slackord/assets/157636771/7cff1516-b59d-4405-81ca-9f8f6db008aa">
<img width="1023" alt="Screenshot 2024-01-24 at 11 44 34 AM" src="https://github.com/thomasloupe/Slackord/assets/157636771/47d2af8e-7f61-4424-93bd-0c93089a219e">
<img width="1025" alt="Screenshot 2024-01-24 at 11 44 57 AM" src="https://github.com/thomasloupe/Slackord/assets/157636771/3601b580-d60e-4fa4-a2bf-b0cd852409e4">
<img width="1025" alt="Screenshot 2024-01-24 at 11 45 54 AM" src="https://github.com/thomasloupe/Slackord/assets/157636771/2ddac9a1-4e57-4f9d-a4aa-170a38b7afaa">
<img width="1022" alt="Screenshot 2024-01-24 at 11 46 35 AM" src="https://github.com/thomasloupe/Slackord/assets/157636771/e7ec9c7a-06a7-43fa-8151-c7490286f3bf">

**Comment by vertis** [comment]
I suspect the problem is that you're inadvertently selecting a file/folder within the directory. I accidentally did this and got the same message. When I retried and was careful to only enter the folder with the dump is got past this stage.

**Comment by thomasloupe** [comment]
@loversandlasers 
Just want to confirm this is/isn't the case as @vertis has mentioned.

**Comment by thomasloupe** [comment]
Hey @loversandlasers,

I've confirmed this is the issue you're experiencing. If you note in the screenshot before your last, you can see the `channels.json` and `users.json` files there. When you select your root folder as the channel folder as you have done in your reproduction, it's looking inside the channel folder for the `channels` and `users` json files, but they're in the directory above it!

The solution is to select the parent folder above your channel folder as @vertis has so kindly pointed out.
Happy Slackording!
