### ISSUE TITLE
Slackord Crashes Upon JSON Import

### ISSUE THREAD

**Issue by zakdenham** [thomasloupe/Slackord#97]
Slackord version: v4.2.3
 - OS: Mac
 - Version: 14.2.1

After selecting "Import JSON" then navigating to the root folder that was exported from the ZIP archive (downloaded from Slack Export) when "Open" is clicked and data should start to import into Slackord, Slackord crashes. 

<img width="1021" alt="Screenshot 2024-03-19 at 8 32 24 PM" src="https://github.com/thomasloupe/Slackord/assets/10414139/1335115a-0131-4130-96a9-e98d254ee1ae">

System Report Info Below:
[https://www.dropbox.com/scl/fi/cv9vxf3g4cyo42v1bu1vj/Slackord-Error.rtf?rlkey=klrl55d73h2uac4vg59mwf4ql&dl=0](url)

**Comment by thomasloupe** [comment]
Hey there,

Sorry to see you're having this issue. It's likely there's some kind of exception happening strictly with the .NET8 library for Mac. Everyone has been reporting this issue, but I've been unable to track down what exactly is causing it.

More bad news: I will likely be discontinuing the Slackord app for Mac for this exact reason. I'm just unable to pin down the issue appropriately in time to release a decent fix for it, and developing for Mac with .NET8 has become a massive chore, costing me too much time and money for purchasing a developer license.

I know this isn't what you want to hear, but I would highly suggest, if possible, you use the Windows version if at all possible. I will continue to support Slackord for Windows going forward, and if someone with enough time and energy can fix the Mac version, I'd be happy to keep releasing it.

If that's you, feel free to drop me a line in our community Discord server! Happy to hear your feedback, and again, I apologize I wasn't able to deliver a proper Slackord for Mac experience for you.

**Comment by thomasloupe** [comment]
I have discontinued Slackord for Mac due to the plethora of issues received for it, and I have released a new version of Slackord with additional features and bug fixes. If you're willing to run a VM, I think you'll find it much easier to deal with. We'll be happy to assist you setting things up if you like. Feel free to reach out on our community Discord.
